services:
  - type: web
    name: water-monitor-ws
    env: node
    buildCommand: bash ./build.sh
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health